### ISSUE TITLE
Add integration with @tanstack/vue-query

### ISSUE THREAD

**Issue by teziovsky** [vuejs/devtools-next#317]
Hi folks! 👋🏼

Requesting a plugin integration for Vue Devtools that enables quick inspection of features provided by @tanstack/vue-query. This integration would streamline debugging and enhance the development experience for Vue applications utilizing vue-query.

**Comment by alexzhang1030** [comment]
That will be great! We will look into it.

**Comment by sibbl** [comment]
There's already some support available. You can enable it by calling:

```js
app.use(VueQueryPlugin, {
    enableDevtoolsV6Plugin: true
});
```

In your dev tools, a new "Vue query" will pop up and timeline events will appear.

Instead of this, you can also install the `@tanstack/vue-query-devtools` package instead and enable it as a stand-alone component in your website. In comparison to the integrated devtools support, this is [properly documented on their site](https://tanstack.com/query/v5/docs/framework/vue/devtools).

**Comment by alexzhang1030** [comment]
> There's already some support available. You can enable it by calling:
> 
> 
> 
> ```js
> 
> app.use(VueQueryPlugin, {
> 
>     enableDevtoolsV6Plugin: true
> 
> });
> 
> ```
> 
> 
> 
> In your dev tools, a new "Vue query" will pop up and timeline events will appear.
> 
> 
> 
> Instead of this, you can also install the `@tanstack/vue-query-devtools` package instead and enable it as a stand-alone component in your website. In comparison to the integrated devtools support, this is [properly documented on their site](https://tanstack.com/query/v5/docs/framework/vue/devtools).

Awesome 🤩

**Comment by sibbl** [comment]
Okay, I just found the following work item which summarizes the missing V7+ support: https://github.com/TanStack/query/issues/7228

So enable the option with care 👍
