### ISSUE TITLE
Hide select component button on seperate window

### ISSUE THREAD

**Issue by alexzhang1030** [vuejs/devtools-next#540]
This comes with another issue. 
- From separate window
- Click select component button (Attachment 1)
- Select a component in the page
- Floating panel appears, it should not based on my settings (Always hide), 
- And it doesn't disappear without clicking somewhere else, causing you to lose the selected component scope. 

<img width="1210" alt="Screenshot 2024-07-22 at 17 30 44" src="https://github.com/user-attachments/assets/2a68ebbe-5fd8-415e-80a4-430b112921b5">

_Originally posted by @atilkan in https://github.com/vuejs/devtools-next/issues/459#issuecomment-2243133762_

**Comment by alexzhang1030** [comment]
> @webfansplz @alexzhang1030 At least let us configure the button setting, seems you resolved this issue by making some assumptions 

Well, inspect button in separate window is nonsense😂

**Comment by jeremy-mcalps** [comment]
@alexzhang1030 

I don't understand why this was the solution to the original problem. I have been using this plugin on v7.3.5 for a while now and I just updated today to the latest version and noticed that the select component in separate window feature was gone. I tracked it down to this PR and saw it was removed altogether. The feature worked perfectly fine for me, so I don't understand why it was removed? 

I have been dealing with the annoying overlay popping up when using the feature in the past, but now the plugin is unusable for me completely because I prefer the separate window workflow. I have the setting selected where the overlay does not show by default so my expected behavior would be that I can use the button (in separate window) to click a component on the page and since I did it from the separate window and I have the overlay setting disabled, the overlay on the page will not open.

I now have to revert to v7.3.5 and cannot get updates because without this feature it is impossible to inspect a component from within the separate window.

Can this be addressed?

**Comment by dragomirweb** [comment]
An approachable way would be threw the config, then it will allow us to customize without breaking your current direction of doing things. Having the standalone server version means for us we can keep up with updates customize it and have good window management. Thanks for your understanding 

The floating window thing breaks my heart.
@jeremy-mcalps there is a trick you can use because currenty is not working as intended ... in the separate window if you click the components tab then press ctrl+s then click somewhere in the app it will inspect that component ( sometimes it doesn't work) this will also cause the floating thing to pop :)
